baseURL = "https://cronokirby.github.io/"
languageCode = "en-us"
title = "ShibaCalc"
theme = "hyde-hyde"
disqusShortname = "cronokirby-github-io"

[params]
    highlightjsstyle = "atom-one-light"
    highlightjs = true
    authorimage = "img/hugo.png"

[params.social]
    github = "cronokirby"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifer = "about"
    weight = 300
    url = "/about/"